### ISSUE TITLE
Differences Between Applicant's Callsign and RegEx

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#216] opened 2020-10-20 12:30 UTC
**Describe the bug**
I had someone apply to our crew center and they put their callsign as Thai 1017V but when I went to User Management it said their callsign was Thai 6502V. Then when the pilot changed it in their profile it was corrected.

**To Reproduce**
1. Apply with correct callsign
2. Administrator sees callsign and sees error

**Expected behavior**
The same callsign is shown everywhere and it is the callsign the applicant originally used.

**Screenshots**
Not required

**Debugging Panel**
![Screen Shot 2020-10-20 at 8 30 22 AM](https://user-images.githubusercontent.com/71337097/96586105-803ca680-12ae-11eb-829c-1a575cf14900.png)

**Additional context**
None :)

**Comment by Velocity23** [comment] 2020-10-20 23:16
Can't reproduce this, but it should be fixed with a authentication update in the next push.

**Closed by Velocity23** 2020-10-20 23:16 UTC
Labels: bug
