### ISSUE TITLE
Plugins Not Installing

### ISSUE THREAD

**Issue by CaptainZac1** [va-net/flare#296] opened 2021-01-02 02:26 UTC
**Describe the bug**
I click install and it just dosen't install

**To Reproduce**
1. Go to plugins
2. Install plugin

**Expected behavior**
Plugin should install but... well it does not. (PS: I tried this on different devices, differnt WiFi connections and none of them work.)

**Comment by velocity23** [comment] 2021-01-03 05:39
@CaptainZac1 I can't reproduce this anywhere using the example plugin, so may I ask what plugin you are trying to install?

**Comment by CPTWilliamSE** [comment] 2021-01-05 08:27
We are able to reproduce on our test site V1.1.1

We tried installing the plugins on two occasions. Both before and after removing the install folder. The plugin folders seem to install into the website although they do not visually appear on the menu tab or on the installed plugins list. The plugins however are installed and accessible through the correct link.

**Comment by velocity23** [comment] 2021-01-05 12:23
That makes life easy, thanks. I'll take a look.

**Comment by velocity23** [comment] 2021-01-07 11:50
Fixed in the next one

**Closed by velocity23** 2021-01-07 11:50 UTC
Labels: bug
