### ISSUE TITLE
No Content on Events Details Page

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#166] opened 2020-09-17 13:16 UTC
**Describe the bug**
Once I have created an event and have put in all the information, if you go to the area to view events, there is no information where the variables would be. 
**To Reproduce**
1. Go to 'Operations Management'
2. Click on 'Manage Events'
3. Click on 'New Event'
4. Fill out the variables
5. Go to 'Events' on the Pilot Panel
6. Expand the event
7. See error

**Expected behavior**
What I expected to happen was for the pilots to be able to see information such as aircraft, departure time, airports etc.

**Screenshots**
![Screen Shot 2020-09-17 at 9 15 32 AM](https://user-images.githubusercontent.com/71337097/93475206-5adf0600-f8c6-11ea-8a5b-cd386c3af3b4.png)

**Additional context**
I have found other Events issues recently and after using my 'mini-fix' for the others, I was able to provide all the steps for this one.

**Comment by Velocity23** [comment] 2020-09-18 06:34
Can't reproduce this @samdog2727, still an issue for you? Could be rate limiting again.

**Comment by samdog2727** [comment] 2020-09-18 12:42
@Velocity23 , I just looked and it is still an issue.

**Comment by Velocity23** [comment] 2020-09-18 23:19
Not sure what's going on here, I'll try pushing the events file as part of Beta 11 to see if it fixes it. Closing for now, just lmk if it's still an issue after the next push and I'll reopen this.

**Comment by Velocity23** [comment] 2020-09-19 00:09
Still an issue in Beta 11

**Comment by Velocity23** [comment] 2020-09-19 00:14
Was a rate limiting thing, changed the limit and it works now

**Closed by Velocity23** 2020-09-19 00:14 UTC
Labels: bug, vanet
