### ISSUE TITLE
Custom Apply Questions

### ISSUE THREAD

**Issue by CPTWilliamSE** [va-net/flare#298] opened 2021-01-06 18:50 UTC
**Is your feature request related to a problem? Please describe.**
The current apply page is a bit lacking in some aspects and quite limiting which means that we have to use outside resources to be able to take in new applicants.

**Describe the solution you'd like**
I'd like for there to be something similar to the "Custom Menu Items" plugin but for the applications page. The ability to add new custom questions to the application page with its own answer box. Having an admin page where all of this info is displayed would be needed too.

**Describe alternatives you've considered**
One could also call this a customizable form.

**Additional context**
I see there is a part of the roadmap in 1.2.0 for forms although im unsure if it is meant for this purpose.
Thanks to the devs for developing this platform.

**Comment by velocity23** [comment] 2021-01-07 11:51
Duplicate of a plugin request, we won't be adding this as a core feature.
https://github.com/va-net/flare-plugins/issues/5

**Closed by velocity23** 2021-01-07 11:51 UTC
Labels: enhancement
