### ISSUE TITLE
Administration Permissions Not Appearing

### ISSUE THREAD

**Issue by TheWheelDaddy** [va-net/flare#186] opened 2020-09-28 15:22 UTC
I have given staff members on our team admin permissions. 

They cannot see their granted permissions at all.

Wondering is this a bug?
I have all my admin permissions and I believe our CEO is the same as me. It is the staff who only need specific permissions such as only PIREP management, etc. that are not seeing their admin panel.

Thank you!

**Comment by Velocity23** [comment] 2020-09-30 04:58
Found the root cause of this (I think), closing for now since it's something completely different.

**Closed by Velocity23** 2020-09-30 04:58 UTC
